site_name: 原石计划MOD文档
site_dir: 'docs'
docs_dir: 'src'

theme:
    name: material
    language: 'zh'
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
    feature:
      tabs: true
    


# pages:
#   - 快速开始: QuickStart.md
#   - 数值表-Database.xls: Database.md
#   - 卡牌指令-CardCommand: CardCommand.md
#   - CardCommand: CardCommand/*
#   - 快捷键: Hotkey.md
#   - 更多文档正在添加中...: More.md



extra:
  search:
    language: 'zh'

  awesome-pages:
    filename: pages.yml
    collapse_single_pages: false

extra_javascript:
  - 'jquery.min.js'
  - 'extra.js'

  
# pages:
#   - AliveGameStudio: AliveGameStudio/index.md
#   - 原石计划: TetraProject/index.md
  # disqus: 'alivegamestudio'